name: Build AGS Config

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build the dotfiles
        run: nix build .#nixosConfigurations.nixos.config.system.build.homeManagerConfigurations.demeter --impure

      - name: Upload AGS config as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ags-config
          path: result/files/.config/ags
